# Generated by Django 5.2.5 on 2025-08-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_id',
        ),
    ]
